/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bus_mgmt;

import javax.swing.JOptionPane;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;


public class Bus_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Bus_Menu
     */
    public Bus_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel()
        {
            public void paintComponent(Graphics g)
            {
                Image img=Toolkit.getDefaultToolkit().getImage(Bus_Menu.class.getResource("/images/img33.jpg"));
                g.drawImage(img,0,0,this.getWidth(),this.getHeight(),this);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new JPanel()
        {
            public void paintComponent(Graphics g)
            {
                Image img=Toolkit.getDefaultToolkit().getImage(log_in.class.getResource("/images/bus1.png"));
                g.drawImage(img,0,0,this.getWidth(),this.getHeight(),this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        routeitem = new javax.swing.JMenuItem();
        bus_detail_item = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        bus_stop = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        driver_detail_item = new javax.swing.JMenuItem();
        student_item = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        Student_item = new javax.swing.JMenuItem();
        logout_menu = new javax.swing.JMenu();
        logoutmenuitem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU FORM");
        setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("GLOBAL");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setText("MANAGEMENT");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setText("SYSTEM");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel5.setText("TRANSPORT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel5)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel2)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel3))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jMenu1.setBackground(new java.awt.Color(153, 255, 255));
        jMenu1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\BAL\\Documents\\NetBeansProjects\\Bus_Mgmt\\src\\images\\log_icon.png")); // NOI18N
        jMenu1.setText("Data Entry");
        jMenu1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(255, 153, 255));
        jMenuItem1.setText("Driver Info");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem4.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuItem4.setForeground(new java.awt.Color(255, 153, 255));
        jMenuItem4.setText("student Info");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        routeitem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        routeitem.setForeground(new java.awt.Color(255, 153, 255));
        routeitem.setText("Route Details");
        routeitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routeitemActionPerformed(evt);
            }
        });
        jMenu1.add(routeitem);

        jMenuBar1.add(jMenu1);

        bus_detail_item.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bus_detail_item.setIcon(new javax.swing.ImageIcon("C:\\Users\\BAL\\Documents\\NetBeansProjects\\Bus_Mgmt\\src\\images\\new_doc.png")); // NOI18N
        bus_detail_item.setText("Data Retrieval");
        bus_detail_item.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(255, 153, 255));
        jMenuItem2.setText("Data Retrieval");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        bus_detail_item.add(jMenuItem2);

        jMenuBar1.add(bus_detail_item);

        bus_stop.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bus_stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_icon.png"))); // NOI18N
        bus_stop.setText("Scheduling");
        bus_stop.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuItem3.setForeground(new java.awt.Color(255, 153, 255));
        jMenuItem3.setText("Bus Scheduling");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        bus_stop.add(jMenuItem3);

        jMenuBar1.add(bus_stop);

        jMenu4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_icon.png"))); // NOI18N
        jMenu4.setText("Service Log");
        jMenu4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N

        driver_detail_item.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        driver_detail_item.setForeground(new java.awt.Color(255, 153, 255));
        driver_detail_item.setText("Service Log");
        driver_detail_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driver_detail_itemActionPerformed(evt);
            }
        });
        jMenu4.add(driver_detail_item);

        jMenuBar1.add(jMenu4);

        student_item.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        student_item.setIcon(new javax.swing.ImageIcon("C:\\Users\\BAL\\Documents\\NetBeansProjects\\Bus_Mgmt\\src\\images\\save1.png")); // NOI18N
        student_item.setText("Accident Log");
        student_item.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuItem5.setForeground(new java.awt.Color(255, 153, 255));
        jMenuItem5.setText("Accident Log");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        student_item.add(jMenuItem5);

        jMenuBar1.add(student_item);

        jMenu2.setText(" Consumption");
        jMenu2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N

        jMenuItem6.setBackground(new java.awt.Color(255, 102, 255));
        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuItem6.setText("Consumption");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_icon.png"))); // NOI18N
        jMenu6.setText("Cars");
        jMenu6.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N

        Student_item.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Student_item.setForeground(new java.awt.Color(255, 153, 255));
        Student_item.setText("College Cars");
        Student_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Student_itemActionPerformed(evt);
            }
        });
        jMenu6.add(Student_item);

        jMenuBar1.add(jMenu6);

        logout_menu.setBackground(new java.awt.Color(153, 255, 255));
        logout_menu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        logout_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit1.png"))); // NOI18N
        logout_menu.setText("Logout");
        logout_menu.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        logout_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_menuActionPerformed(evt);
            }
        });

        logoutmenuitem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logoutmenuitem.setForeground(new java.awt.Color(255, 153, 255));
        logoutmenuitem.setText("Logout");
        logoutmenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutmenuitemActionPerformed(evt);
            }
        });
        logout_menu.add(logoutmenuitem);

        jMenuBar1.add(logout_menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logout_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logout_menuActionPerformed

    private void logoutmenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutmenuitemActionPerformed
        // TODO add your handling code here:
        log_in l=new log_in();
        l.setVisible(true);
         this.hide();

    }//GEN-LAST:event_logoutmenuitemActionPerformed

    private void driver_detail_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driver_detail_itemActionPerformed
        // TODO add your handling code here:
        try{
            
         this.hide();
        Service_Log di=new Service_Log();
        
        di.setVisible(true);
//        di.btdelete.setEnabled(false);
//        di.btreset.setEnabled(false);
//        di.btupdate.setEnabled(false);
        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
        
    }//GEN-LAST:event_driver_detail_itemActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        try {
            // TODO add your handling code here:
            Accident_Log sii=new Accident_Log();
            sii.setVisible(true);
            this.hide();
        } catch (Exception ex) {
            Logger.getLogger(Bus_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void Student_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Student_itemActionPerformed
        // TODO add your handling code here:
        this.hide();
        cars cr=new cars();
        cr.setVisible(true);
    }//GEN-LAST:event_Student_itemActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.hide();
       Bus_Receipt dtr=new Bus_Receipt();
        dtr.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.hide();
        Scheduling_Bus sb=new Scheduling_Bus();
        sb.setVisible(true);
        
        
    }//GEN-LAST:event_jMenuItem3ActionPerforme

    private void routeitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routeitemActionPerformed
        // TODO add your handling code here:
        
        try {
            // TODO add your handling code here:
            this.hide();
             Bus_Route dd=new Bus_Route();
            dd.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Bus_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_routeitemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            // TODO add your handling code here:
            this.hide();
            Driver_Info dd=new Driver_Info();
            dd.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Bus_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            this.hide();
            student_info si=new student_info();
            si.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Bus_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            this.hide();
            PetrolConsumption si=new PetrolConsumption();
            si.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Bus_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bus_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bus_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bus_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bus_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bus_Menu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Student_item;
    private javax.swing.JMenu bus_detail_item;
    private javax.swing.JMenu bus_stop;
    private javax.swing.JMenuItem driver_detail_item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu logout_menu;
    private javax.swing.JMenuItem logoutmenuitem;
    private javax.swing.JMenuItem routeitem;
    private javax.swing.JMenu student_item;
    // End of variables declaration//GEN-END:variables
}
