/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bus_mgmt;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JPanel;



/**
 *
 * @author ICS
 */


public class student_info extends javax.swing.JFrame {

   PreparedStatement ps;
    String sql=null;
    Connection conn;

    
    public student_info() throws SQLException {
        initComponents();
        try{
            
        connect_db d=new connect_db();
        conn=DriverManager.getConnection(d.ss, d.stuid,d.stupw);
        }
        catch(Exception e)
        {
            System.out.println(e);;
        }
    }

    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel()
        {
            public void paintComponent(Graphics g)
            {
                Image img=Toolkit.getDefaultToolkit().getImage(student_info.class.getResource("/images/ss.jpg"));
                g.drawImage(img,0,0,this.getWidth(),this.getHeight(),this);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        txtstuid = new javax.swing.JLabel();
        stuname = new javax.swing.JLabel();
        txtdept = new javax.swing.JLabel();
        txtroute = new javax.swing.JLabel();
        txtsem = new javax.swing.JLabel();
        txtfeepaid = new javax.swing.JLabel();
        txtdues = new javax.swing.JLabel();
        txtbustop = new javax.swing.JLabel();
        txtbustime = new javax.swing.JLabel();
        txtrec = new javax.swing.JLabel();
        txtstudentid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtfee = new javax.swing.JTextField();
        txtdue = new javax.swing.JTextField();
        txtrecp = new javax.swing.JTextField();
        btsave = new javax.swing.JButton();
        btdelete = new javax.swing.JButton();
        btreset = new javax.swing.JButton();
        btupdate = new javax.swing.JButton();
        btinfo = new javax.swing.JButton();
        txtbatch = new javax.swing.JLabel();
        cmdept = new javax.swing.JComboBox();
        cmsem = new javax.swing.JComboBox();
        cmyear = new javax.swing.JComboBox();
        cmbustime = new javax.swing.JComboBox();
        cmbus = new javax.swing.JComboBox();
        btcancel = new javax.swing.JButton();
        txtrouteno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("STUDENT INFORMATION");

        txtstuid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtstuid.setText("Student Id");

        stuname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        stuname.setText("Name");

        txtdept.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtdept.setText("Department");

        txtroute.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtroute.setText("Route No");

        txtsem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtsem.setText("Semester");

        txtfeepaid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtfeepaid.setText("Fee Paid ");

        txtdues.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtdues.setText("Dues");

        txtbustop.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtbustop.setText("Bus Stop");

        txtbustime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtbustime.setText("Bus Time ");

        txtrec.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtrec.setText("Recp No ");

        btsave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btsave.setIcon(new javax.swing.ImageIcon("C:\\Users\\BAL\\Documents\\NetBeansProjects\\Bus_Mgmt\\src\\images\\save1.png")); // NOI18N
        btsave.setText("Save");
        btsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaveActionPerformed(evt);
            }
        });

        btdelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btdelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\BAL\\Documents\\NetBeansProjects\\Bus_Mgmt\\src\\images\\delete1.png")); // NOI18N
        btdelete.setText("Delete");
        btdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeleteActionPerformed(evt);
            }
        });

        btreset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btreset.setText("Reset");
        btreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btresetActionPerformed(evt);
            }
        });

        btupdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btupdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\BAL\\Documents\\NetBeansProjects\\Bus_Mgmt\\src\\images\\software_update.png")); // NOI18N
        btupdate.setText("Update");
        btupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btupdateActionPerformed(evt);
            }
        });

        btinfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btinfo.setText("View Info");
        btinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btinfoActionPerformed(evt);
            }
        });

        txtbatch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtbatch.setText("Batch");

        cmdept.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BCA", "B.COM", "CSE", "CIVIL", "ECE", "IT", "ME", "MCA", "MBA", "DIPLOMA", " ", " ", " ", " " }));

        cmsem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1st", "2nd", "3rd", "4th", "5th", "6th", "7th", "8th" }));
        cmsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmsemActionPerformed(evt);
            }
        });

        cmyear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2011", "2012", "2013", "2014", "2015", "2016", " " }));

        cmbustime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10" }));

        cmbus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tarn Taran", "Daburji", " " }));

        btcancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btcancel.setIcon(new javax.swing.ImageIcon("C:\\Users\\BAL\\Documents\\NetBeansProjects\\Bus_Mgmt\\src\\images\\exit1.png")); // NOI18N
        btcancel.setText("Cancel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btcancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btsave)
                                .addGap(18, 18, 18)
                                .addComponent(btdelete))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtstuid)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtstudentid, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(stuname)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtdept)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                        .addComponent(cmdept, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtsem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmsem, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtbatch)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtroute)
                                                .addGap(45, 45, 45)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmyear, 0, 162, Short.MAX_VALUE)
                                            .addComponent(txtrouteno))))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btreset)
                                .addGap(18, 18, 18)
                                .addComponent(btupdate)
                                .addGap(18, 18, 18)
                                .addComponent(btinfo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtfeepaid)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtfee, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtdues)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtdue, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtbustop)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbus, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtbustime)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbustime, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtrec)
                                        .addGap(42, 42, 42)
                                        .addComponent(txtrecp, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfeepaid)
                            .addComponent(txtfee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtstudentid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtstuid))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stuname)
                            .addComponent(txtdues)
                            .addComponent(txtdue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmdept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdept)
                            .addComponent(txtbustop)
                            .addComponent(cmbus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmsem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsem)
                            .addComponent(txtbustime)
                            .addComponent(cmbustime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtrec)
                            .addComponent(txtrecp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtbatch)))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtroute)
                    .addComponent(txtrouteno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btsave)
                            .addComponent(btcancel)
                            .addComponent(btdelete)
                            .addComponent(btreset))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btupdate)
                            .addComponent(btinfo))
                        .addGap(48, 48, 48))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btresetActionPerformed

    private void btupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btupdateActionPerformed
        // TODO add your handling code here:
        int response=JOptionPane.showConfirmDialog(null,"Do You Want To Update This Record","confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (response==JOptionPane.YES_OPTION) 
        { try {
            String strupdate1="update student_info set Name='"+txtname.getText()+"',Fee_Paid='"+txtfee.getText()+"' where Student_Id='"+txtstudentid.getText()+"'";
            ps=conn.prepareStatement(strupdate1);
            ps.execute();
            JOptionPane.showMessageDialog(this, "Record is updated Successfully");
            txtstuid.setText("");
        txtname.setText("");
        Driver_table dt=new Driver_table();
            dt.show_data();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        }

    }//GEN-LAST:event_btupdateActionPerformed

    private void btinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btinfoActionPerformed
       try {
           // TODO add your handling code here:
           student_table si=new student_table();
           si.setVisible(true);
           this.hide();
       } catch (Exception ex) {
           Logger.getLogger(student_info.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_btinfoActionPerformed

    private void btsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaveActionPerformed
        try{
       sql="insert into student_info(Student_Id,Name,Department,Semester,Year,Route_No,Fee_Paid,Dues,Bus_Stop,Bus_Time,Recp_No)values('"+txtstudentid.getText()+"','"+txtname.getText()+"','"+cmdept.getSelectedItem()+"','"+cmsem.getSelectedItem()+"','"+cmyear.getSelectedItem()+"','"+txtrouteno.getText()+"','"+txtfee.getText()+"','"+txtdue.getText()+"', '"+cmbus.getSelectedItem()+"','"+cmbustime.getSelectedItem()+"','"+txtrecp.getText()+"')";
       ps=conn.prepareStatement(sql);
       ps.execute();
       
           JOptionPane.showMessageDialog(this, "Record Saved Successfully");
       }
       catch(Exception e)
       {
          System.out.println(e);
       }
    }//GEN-LAST:event_btsaveActionPerformed

    private void cmsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmsemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmsemActionPerformed

    private void btdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeleteActionPerformed
        // TODO add your handling code here:
        int response=JOptionPane.showConfirmDialog(null,"do you want to delete","confirm",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
        if(response==JOptionPane.YES_NO_OPTION)
        {
            try{
                String strdel="delete from student_info where Student_Id='"+ txtstudentid.getText()+"'";
                ps=conn.prepareStatement(strdel);
                ps.execute();
                JOptionPane.showMessageDialog(this, "Record is successfully deleted");
                txtstuid.setText("");
                txtname.setText("");
                txtfee.setText("");
                txtdue.setText("");
                txtrec.setText("");
                student_table dt=new student_table();
                this.hide();
                dt.setVisible(true);
                dt.show_data();
              
            }
            catch(Exception e )
            {
                System.out.println(e);
            }

        }
    
    }//GEN-LAST:event_btdeleteActionPerformed

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new student_info().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Driver_Info.class.getName()).log(Level.SEVERE, null, ex);
                }
  
                
            }
        });
            }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcancel;
    private javax.swing.JButton btdelete;
    private javax.swing.JButton btinfo;
    private javax.swing.JButton btreset;
    private javax.swing.JButton btsave;
    private javax.swing.JButton btupdate;
    private javax.swing.JComboBox cmbus;
    private javax.swing.JComboBox cmbustime;
    private javax.swing.JComboBox cmdept;
    private javax.swing.JComboBox cmsem;
    private javax.swing.JComboBox cmyear;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JLabel stuname;
    private javax.swing.JLabel txtbatch;
    public javax.swing.JLabel txtbustime;
    public javax.swing.JLabel txtbustop;
    public javax.swing.JLabel txtdept;
    public javax.swing.JTextField txtdue;
    public javax.swing.JLabel txtdues;
    public javax.swing.JTextField txtfee;
    public javax.swing.JLabel txtfeepaid;
    public javax.swing.JTextField txtname;
    public javax.swing.JLabel txtrec;
    public javax.swing.JTextField txtrecp;
    public javax.swing.JLabel txtroute;
    private javax.swing.JTextField txtrouteno;
    public javax.swing.JLabel txtsem;
    public javax.swing.JTextField txtstudentid;
    public javax.swing.JLabel txtstuid;
    // End of variables declaration//GEN-END:variables
}
