/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bus_mgmt;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;


import javax.swing.JOptionPane;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JPanel;
import net.proteanit.sql.DbUtils;

 
public class student_table extends javax.swing.JFrame {
    
     PreparedStatement ps;
    String sql=null;
    String str=null;
    Connection conn;
    ResultSet rs=null;
    
    public void show_data()
    {
    try{
    String ss="select * from student_info";
    ps=conn.prepareStatement(ss);
    rs=ps.executeQuery();
    stutb.setModel(DbUtils.resultSetToTableModel(rs));
    }catch(Exception e){
    JOptionPane.showMessageDialog(this, e);
    }}
    


    /**
     * Creates new form student_table
     */
    public student_table() {
        initComponents();
         try{
        
        connect_db d=new connect_db();
        conn=DriverManager.getConnection(d.ss,d.stuid,d.stupw);
        show_data();
        }
        catch(Exception e)
        {
            System.out.println(e);;
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel()
        {
            public void paintComponent(Graphics g)
            {
                Image img=Toolkit.getDefaultToolkit().getImage(Bus_Menu.class.getResource("/images/stu.jpg"));
                g.drawImage(img,0,0,this.getWidth(),this.getHeight(),this);
            }
        };
        jScrollPane1 = new javax.swing.JScrollPane();
        stutb = new javax.swing.JTable();
        stu_table = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        stutb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        stutb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stutb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        stutb.setGridColor(new java.awt.Color(102, 102, 255));
        stutb.setSelectionBackground(new java.awt.Color(204, 255, 255));
        stutb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stutbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(stutb);

        stu_table.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        stu_table.setForeground(new java.awt.Color(255, 255, 255));
        stu_table.setText("Student Information");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(stu_table)
                .addContainerGap(330, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(stu_table)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void stutbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stutbMouseClicked
        // TODO add your handling code here:
          try
        {

            // show_data();
            int row=stutb.getSelectedRow();
            String table_click=stutb.getModel().getValueAt(row,0).toString();
            str="select * from student_Info where Student_Id='"+table_click+"'";
            ps=conn.prepareStatement(str);
            rs=ps.executeQuery();
            if(rs.next())
            {
                //Driver_Info d=new Driver_Info();
                String stuid = rs.getString("Student_Id");
                //d.txtid.setText(id);

                String sname=rs.getString("Name");
                //d.txtname.setText(name);

                //String dept = rs.getString("Department");

                //String sem=rs.getString("Semester");

               // String yr = rs.getString("Year");

                //String route=rs.getString("Route_No");

                String fee = rs.getString("Fee_Paid");

                String dues=rs.getString("Dues");

                //String bustop = rs.getString("Bus_Stop");

                //String bustime=rs.getString("Bus_Time");
                 String recp=rs.getString("Recp_No");

                show_data();
                student_info sr=new student_info();
                sr.setVisible(true);
                sr.txtstudentid.setText(stuid);
                sr.txtname.setText(sname);
                //sr.txtdept.setText(dept);
                //sr.txtsem.setText(sem);
               // sr.txtroute.setText(yr);
               sr.txtfee.setText(fee);
                sr.txtdue.setText(fee);
                sr.txtbustop.setText(dues);
               // sr.txtbustime.setText(bustime);
                sr.txtrecp.setText(recp);
                this.hide();

                //txtid.setText(id);
            }
            //Driver_Info dr=new Driver_Info();
            //dr.setVisible(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
                                         


    }//GEN-LAST:event_stutbMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student_table().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel stu_table;
    private javax.swing.JTable stutb;
    // End of variables declaration//GEN-END:variables
}
